# Use the official Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY main.py .

# Specify the command to run the script
CMD ["python", "main.py"]
