version: '3.8'

services:
  bitcoind:
    build: .
    ports:
      - "8333:8333"  # P2P network
      - "8332:8332"  # RPC interface
    volumes:
      - ./bitcoin_data:/data  # 数据卷挂载
    command: ["bitcoind", "-datadir=/data"]
